package com.appVersion;

import java.util.ArrayList;
import java.util.List;

import com.master.model.GeneralMasterModel;

public class VehicleMakeData {
	
	List<Object>versionControlDataList=new ArrayList<Object>();
	Long parentId=null;

	public void vehicleMakeData(){
		versionControlDataList.add(new GeneralMasterModel("VMK0001","AC","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0002","Acura","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0003","Aixam","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0004","Alfa Romeo","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0005","Alpina","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0006","Alpine","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0007","AMC","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0008","ARO","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0009","Asia Motors","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0010","Aston Martin","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0011","Audi","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0012","Austin","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0013","Austin-Healey","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0014","Auto Union","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0015","Autobianchi","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0016","Barkas","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0017","Bedford","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0018","Bentley","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0019","Bertone","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0020","Bitter","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0021","BMW","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0022","Bond","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0023","Borgward","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0024","Bristol","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0025","Bugatti","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0026","Buick","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0027","Cadillac","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0028","Callaway","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0029","Carbodies","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0030","Caterham","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0031","Checker","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0032","Chevrolet","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0033","Chrysler","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0034","Citroën","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0035","Dacia","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0036","Daewoo","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0037","DAF","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0038","Daihatsu","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0039","Daimler","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0040","Dallas","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0041","De Lorean","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0042","De Tomaso","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0043","Dodge","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0044","Ebro","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0045","Ferrari","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0046","Fiat","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0047","Fisker","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0048","Ford","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0049","Foton","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0050","FSO","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0051","GAZ","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0052","Geely","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0053","Geo","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0054","Ginetta","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0055","Glas","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0056","GMC","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0057","Golden Dragon","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0058","GREAT WALL","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0059","Hindustan","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0060","Holden","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0061","Honda","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0062","Hummer","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0063","Hyundai","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0064","Indigo","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0065","Infiniti","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0066","Innocenti","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0067","Irmscher","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0068","Isdera","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0069","ISH","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0070","Isuzu","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0071","Iveco","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0072","Jaguar","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0073","Jeep","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0074","Jensen","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0075","Jiangling Landwind","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0076","Kia","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0077","KTM","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0078","Lada","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0079","Lamborghini","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0080","Lancia","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0081","Land Rover","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0082","LDV","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0083","Lexus","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0084","Ligier","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0085","Lincoln","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0086","Lotus","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0087","LTI","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0088","Mahindra","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0089","Marcos","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0090","Maserati","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0091","Maxus","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0092","Maybach","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0093","Mazda","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0094","Mclaren","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0095","Mega","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0096","Mercedes-Benz","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0097","Metrocab","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0098","MG","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0099","Middlebridge","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0100","Mini","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0101","Mitsubishi","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0102","Morgan","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0103","Morris","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0104","Moskvich","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0105","Nissan","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0106","NOBLE","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0107","NSU","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0108","Oldsmobile","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0109","Oltcit","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0110","Opel","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0111","Osca","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0112","Panoz","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0113","Panther","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0114","Paykan","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0115","Perodua","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0116","Peugeot","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0117","Piaggio","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0118","Pininfarina","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0119","Plymouth","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0120","Pontiac","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0121","Porsche","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0122","Premier","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0123","Proton","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0124","Puch","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0125","Ranger","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0126","Rayton Fissore","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0127","Reliant","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0128","Renault","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0129","Riley","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0130","Rolls-Royce","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0131","Rover","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0132","Saab","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0133","Santana","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0134","Seat","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0135","Shelby","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0136","Sipani","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0137","Skoda","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0138","Smart","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0139","Spectre","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0140","Spyker","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0141","Ssangyong","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0142","Standard","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0143","Streetscooter’","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0144","Subaru","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0145","Suzuki","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0146","Talbot","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0147","Tata","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0148","Tesla","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0149","Toyota","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0150","Trabant","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0151","Triumph","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0152","TVR","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0153","UAZ","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0154","UMM","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0155","Vauxhall","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0156","Vector","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0157","Volvo","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0158","VW","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0159","Wartburg","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0160","Westfield","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0161","Wiesmann","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0162","Wolseley","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0163","Yugo","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0164","Yulon","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0165","Zastava","",parentId));
		versionControlDataList.add(new GeneralMasterModel("VMK0166","ZAZ","",parentId));

	}

}
